import assert from "node:assert/strict";
import {test} from "node:test";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import {createHash} from "node:crypto";
import {createMonetaryV2PaymentClient,createVerifiedMonetaryV2Payment,monetaryV2PaymentCanonical,monetaryV2PaymentOperationId,createMonetaryV2Review} from "../src/monetary-v2-payment-client.js";
import {createLocalFilePaymentAuthorityFence,createMonetaryV2EventRouter,createMonetaryV2XsollaComposition} from "../src/monetary-v2-xsolla-composition.js";
import {configureLocalMonetaryV2Payments} from "../src/monetary-v2-payment-bootstrap.js";
const digest=s=>createHash("sha256").update(s).digest("hex");
const recipient="ABC123";
function receipt(){return{provider:"xsolla",providerTransactionId:"9223372036854775807",transactionId:"9223372036854775807",userId:recipient,playFabId:recipient,environment:"sandbox",source:"xsolla_sandbox",productId:"diamond_pack_1",xsollaSku:"seabyss_diamond_pack_1",productType:"diamond_pack",productPlanVersion:2,currency:"USD",unitAmountMinor:199,totalAmountMinor:199,quantity:1,promotionPolicy:"disabled"};}
const request=(alias="xsd2")=>createVerifiedMonetaryV2Payment(receipt(),{environment:"sandbox",titleId:"1D0C16",receiptAlias:alias});
const options={enabled:true,environment:"sandbox",titleId:"1D0C16",origin:"http://127.0.0.1:55160/",token:"T".repeat(64)};
function result(p,status="Completed"){return{status,operationId:monetaryV2PaymentOperationId(p),canonicalPayloadSha256:p.canonicalPayloadSha256,committed:status==="Completed"?{operationId:monetaryV2PaymentOperationId(p),payloadHash:"c".repeat(64),accounts:[{account:p.recipient,sequence:1,headHash:"a".repeat(64),gold:0,diamonds:1000,ownerEpoch:1}]}:null,reviewReason:status==="ManualReview"?"legacy_ambiguous":null};}
const response=(p,status="Completed")=>({status:status==="Pending"?202:200,body:JSON.stringify(result(p,status))});
function fixture(){const directory=fs.mkdtempSync(path.join(os.tmpdir(),"monetary-v2-fence-"));const filePath=path.join(directory,"fence.jsonl");const settings={filePath,environment:"sandbox",titleId:"1D0C16"};const fence=createLocalFilePaymentAuthorityFence({...settings,initialize:true});return{directory,settings,fence,close(){fs.rmSync(directory,{recursive:true,force:true});}};}
const proof=(mode="V2")=>({environment:"sandbox",titleId:"1D0C16",recipient,mode,epoch:1,sourceHash:"b".repeat(64)});
test("default disabled makes zero transport calls",async()=>{let calls=0;const c=createMonetaryV2PaymentClient({transport:()=>{calls++;}});await assert.rejects(()=>c.submit(createVerifiedMonetaryV2Payment(receipt(),{environment:"local",titleId:"LOCAL"})));assert.equal(calls,0);assert.equal(configureLocalMonetaryV2Payments(),null);});
test("production title and remote URLs rejected",()=>{for(const change of [{titleId:"142853"},{environment:"production"},{origin:"https://142853.playfabapi.com/"},{origin:"http://localhost:55160/"},{origin:"http://127.0.0.1:55160/path"},{origin:"http://user@127.0.0.1:55160/"}])assert.throws(()=>createMonetaryV2PaymentClient({...options,...change}));});
test("canonical proof uses lossless ID and alias-independent economics",()=>{const a=request(),b=request("xsd1");assert.equal(a.transactionId,"9223372036854775807");assert.equal(a.canonicalPayloadSha256,b.canonicalPayloadSha256);assert.equal(monetaryV2PaymentOperationId(a),monetaryV2PaymentOperationId(b));assert.equal(a.canonicalPayloadSha256,digest(monetaryV2PaymentCanonical(a)));assert.throws(()=>createVerifiedMonetaryV2Payment({...receipt(),transactionId:9223372036854776000},{environment:"sandbox",titleId:"1D0C16"}));});
test("immutable catalog rejects changed price quantity recipient alias family",()=>{for(const change of [{totalAmountMinor:1},{quantity:2},{userId:"OTHER"},{productPlanVersion:999},{source:"xsolla_production"}])assert.throws(()=>createVerifiedMonetaryV2Payment({...receipt(),...change},{environment:"sandbox",titleId:"1D0C16"}));assert.throws(()=>request("xss2"));});
test("private exact body and token header only",async()=>{const p=request();const c=createMonetaryV2PaymentClient({...options,transport:async q=>{assert.equal(q.url.href,"http://127.0.0.1:55160/v2/payments/verified");assert.equal(q.headers["X-Seabyss-Monetary-Token"],options.token);assert.deepEqual(JSON.parse(q.body),p);return response(p);}});assert.equal((await c.submit(p)).status,"Completed");});
for(const status of ["Pending","ManualReview"])test(`${status} is not spendable completion`,async()=>{const p=request();const c=createMonetaryV2PaymentClient({...options,transport:async()=>response(p,status)});assert.equal((await c.submit(p)).committed,null);});
for(const mutate of [r=>({...r,operationId:"wrong"}),r=>({...r,canonicalPayloadSha256:"a".repeat(64)}),r=>({...r,committed:null}),r=>({...r,committed:{...r.committed,accounts:[{account:"OTHER"}]}})])test("malformed or misbound success remains UNKNOWN",async()=>{const p=request();const c=createMonetaryV2PaymentClient({...options,transport:async()=>({status:200,body:JSON.stringify(mutate(result(p)))})});await assert.rejects(()=>c.submit(p),/UNKNOWN/);});
test("response loss and restart replay exact ID/body without double fake grant",async()=>{const p=request(),seen=new Map();let attempts=0;const transport=async q=>{attempts++;const parsed=JSON.parse(q.body),key=monetaryV2PaymentOperationId(parsed);if(seen.has(key))assert.equal(seen.get(key),q.body);else seen.set(key,q.body);if(attempts===1)throw new Error("lost after fake application");return response(p);};await assert.rejects(()=>createMonetaryV2PaymentClient({...options,transport}).submit(p));assert.equal(attempts,1);assert.equal((await createMonetaryV2PaymentClient({...options,transport}).submit(p)).status,"Completed");assert.equal(seen.size,1);});
test("uncooperative transport is bounded",async()=>{const c=createMonetaryV2PaymentClient({...options,timeoutMs:10,transport:()=>new Promise(()=>{})});await assert.rejects(()=>c.submit(request()),/UNKNOWN/);});
test("authority endpoint context must match",async()=>{for(const p of [proof(),{...proof(),titleId:"142853"},{...proof(),mode:"unknown"},{...proof(),recipient:"OTHER"}]){const c=createMonetaryV2PaymentClient({...options,transport:async()=>({status:200,body:JSON.stringify(p)})});if(p.titleId==="1D0C16"&&p.mode==="V2"&&p.recipient===recipient)assert.equal((await c.authority(recipient)).mode,"V2");else await assert.rejects(()=>c.authority(recipient));}});
test("durable V2 fence survives restart and disabled adapter blocks legacy",async()=>{const f=fixture();try{await f.fence.remember(proof());const restarted=createLocalFilePaymentAuthorityFence(f.settings);let legacy=0;const router=createMonetaryV2EventRouter({fence:restarted,legacyProcessor:async()=>legacy++,v2Processor:async()=>{}});await assert.rejects(()=>router({userId:recipient}),/NO_LEGACY/);assert.equal(legacy,0);}finally{f.close();}});
test("positive V1 authority routes only unfenced accounts",async()=>{const f=fixture();try{let legacy=0;const r=createMonetaryV2EventRouter({enabled:true,resolveAuthority:async()=>proof("V1"),fence:f.fence,legacyProcessor:async()=>legacy++,v2Processor:async()=>{}});await r({userId:recipient});await f.fence.remember(proof());await assert.rejects(()=>r({userId:recipient}),/NO_DOWNGRADE/);assert.equal(legacy,1);}finally{f.close();}});
test("unknown and failed authority never fallback",async()=>{const f=fixture();try{let legacy=0;for(const resolveAuthority of [async()=>{throw new Error("loss");},async()=>({...proof(),mode:"unknown"}),async()=>proof("Migrating")]){const r=createMonetaryV2EventRouter({enabled:true,resolveAuthority,fence:f.fence,legacyProcessor:async()=>legacy++,v2Processor:async()=>{}});await assert.rejects(()=>r({userId:recipient}));}assert.equal(legacy,0);}finally{f.close();}});
test("torn durable fence fails closed",async()=>{const f=fixture();try{fs.appendFileSync(f.settings.filePath,'{"recipient":');assert.throws(()=>createLocalFilePaymentAuthorityFence(f.settings));}finally{f.close();}});
test("refund policy produces no automatic grant/clawback/fallback",async()=>{const f=fixture();try{let sent=0,legacy=0;const r=createMonetaryV2XsollaComposition({client:{...options,authority:async()=>proof(),submit:async()=>{sent++;}},fence:f.fence,legacyProcessor:async()=>legacy++});await assert.rejects(()=>r({userId:recipient,notificationType:"refund"}),/DURABLE_MANUAL_REVIEW/);assert.equal(sent,0);assert.equal(legacy,0);}finally{f.close();}});
test("bootstrap rejects production and parallel legacy worker",()=>{for(const config of [{nodeEnv:"production",playFabTitleId:"1D0C16"},{nodeEnv:"test",playFabTitleId:"142853"},{nodeEnv:"test",playFabTitleId:"1D0C16",paymentWorkerEnabled:true}])assert.throws(()=>configureLocalMonetaryV2Payments({env:{SEABYSS_MONETARY_V2_PAYMENTS_ENABLED:"true",SEABYSS_MONETARY_V2_PAYMENT_FENCE_FILE:"test",SEABYSS_MONETARY_V2_PAYMENT_ENVIRONMENT:"sandbox"},config}));});
import {createMemoryXsollaEventStore,createXsollaWebhookHandler} from "../src/xsolla-webhook.js";
function paidEvent(){return{notification_type:"payment",settings:{project_id:310966},user:{id:recipient},transaction:{id:"9223372036854775807",dry_run:1,payment_date:"2026-09-24T00:00:00.000Z"},purchase:{total:{amount:"1.99",currency:"USD"},order:{lineitems:[{sku:"seabyss_diamond_pack_1",quantity:1,price:{amount:"1.99",currency:"USD"}}]}}};}
for(const phase of ["Completed","Pending"])test(`signature/catalog ingress to ${phase} preserves existing handler contract`,async()=>{
    const f=fixture();try{let calls=0,legacy=0;
    const client=createMonetaryV2PaymentClient({...options,transport:async q=>{if(q.body===null)return{status:200,body:JSON.stringify(proof())};calls++;return response(JSON.parse(q.body),phase);}});
    const router=createMonetaryV2XsollaComposition({client,fence:f.fence,legacyProcessor:async()=>{legacy++;return "legacy";},
        hardenedOptions:{allowDiamondSandboxGrants:true,diamondSandboxTestPlayFabIds:[recipient],validateUser:async()=>true},
        gateOptions:{globalEnabled:true,familyGates:{diamond_pack:true},allowedSkus:["seabyss_diamond_pack_1"]}});
    const handler=createXsollaWebhookHandler({webhookSecret:"offline-test-secret",projectId:"310966",eventStore:createMemoryXsollaEventStore(),processEvent:router});
    const body=Buffer.from(JSON.stringify(paidEvent())),signature=createHash("sha1").update(body).update("offline-test-secret").digest("hex");
    const res={code:0,status(c){this.code=c;return this;},json(){return this;},end(){return this;}};
    await handler({body,get:n=>n.toLowerCase()==="authorization"?`Signature ${signature}`:undefined},res);
    assert.equal(res.code,204);assert.equal(calls,1);assert.equal(legacy,0);
    }finally{f.close();}
});
test("invalid signature never reaches authority or fulfillment",async()=>{
    let calls=0;const handler=createXsollaWebhookHandler({webhookSecret:"offline-test-secret",projectId:"310966",eventStore:createMemoryXsollaEventStore(),processEvent:async()=>{calls++;return "invalid";}});
    const res={code:0,status(c){this.code=c;return this;},json(){return this;},end(){return this;}};
    await handler({body:Buffer.from(JSON.stringify(paidEvent())),get:()=>"Signature "+"0".repeat(40)},res);assert.equal(calls,0);assert.notEqual(res.code,204);
});
test("V2 fence rejects stale epoch and conflicting same-epoch proof",async()=>{const f=fixture();try{await f.fence.remember({...proof(),epoch:2});await assert.rejects(()=>f.fence.remember(proof()),/STALE/);await assert.rejects(()=>f.fence.remember({...proof(),epoch:2,sourceHash:"c".repeat(64)}),/CONFLICTING/);}finally{f.close();}});
test("completed snapshots require valid hash balances and sequence",async()=>{const p=request();for(const change of [{diamonds:-1},{diamonds:2147483648},{sequence:0},{headHash:"bad"},{ownerEpoch:0}]){const r=result(p);r.committed.accounts[0]={...r.committed.accounts[0],...change};const c=createMonetaryV2PaymentClient({...options,transport:async()=>({status:200,body:JSON.stringify(r)})});await assert.rejects(()=>c.submit(p),/UNKNOWN/);}});
test("signed reversal route uses existing parser and durable private review only",async()=>{const f=fixture();try{let reviews=0,legacy=0,grants=0;const client=createMonetaryV2PaymentClient({...options,transport:async q=>{if(q.body===null)return{status:200,body:JSON.stringify(proof())};assert.equal(q.url.pathname,"/v2/payments/review");reviews++;const p=JSON.parse(q.body);return{status:200,body:JSON.stringify({status:"ManualReview",operationId:"xsolla_"+digest(`${p.environment}\n${p.titleId}\n${p.transactionId}`),reversalEventId:p.reversalEventId,evidenceSha256:p.evidenceSha256,policy:"manual_review_no_automatic_clawback",correlation:"Matched"})};}});
 const route=createMonetaryV2XsollaComposition({client,fence:f.fence,legacyProcessor:async()=>legacy++});
 const payload={notification_type:"refund",settings:{project_id:310966},user:{id:recipient},purchase:{total:{amount:"1.99",currency:"USD"}},transaction:{id:"9223372036854775807"},refund_details:{code:4,reason:"Local test",author:"test",date:"2026-09-24T00:00:00Z"}};
 assert.equal(await route({payload,notificationType:"refund",userId:recipient}),"monetary_v2_reversal_manual_review");assert.equal(reviews,1);assert.equal(grants,0);assert.equal(legacy,0);
 }finally{f.close();}});
test("reversal requires truthful correlation and exact normalized body",async()=>{
 const reversal={providerTransactionId:"9223372036854775807",expectedPlayFabId:recipient,reversalEventId:"xsolla:refund:"+"d".repeat(64),amountMinor:199,currency:"USD",type:"refund"};
 const p=createMonetaryV2Review(reversal,"refund",options);
 for(const correlation of [undefined,"Assumed","Matched","Unmatched"]){const c=createMonetaryV2PaymentClient({...options,transport:async()=>({status:200,body:JSON.stringify({status:"ManualReview",operationId:"xsolla_"+digest(`${p.environment}\n${p.titleId}\n${p.transactionId}`),reversalEventId:p.reversalEventId,evidenceSha256:p.evidenceSha256,policy:"manual_review_no_automatic_clawback",correlation})})});if(["Matched","Unmatched"].includes(correlation))assert.equal((await c.review(p)).correlation,correlation);else await assert.rejects(()=>c.review(p),/UNKNOWN/);}
 assert.throws(()=>createMonetaryV2Review({...reversal,type:"chargeback"},"refund",options),/differ/);
});
function appendFenceRecord(filePath,p){fs.appendFileSync(filePath,JSON.stringify({recipient:p.recipient,epoch:p.epoch,sourceHash:p.sourceHash,sha256:digest(JSON.stringify([p.recipient,p.epoch,p.sourceHash]))})+"\n");}
test("disk replay rejects a later lower epoch after restart",async()=>{const f=fixture();try{await f.fence.remember({...proof(),epoch:2});appendFenceRecord(f.settings.filePath,proof());assert.throws(()=>createLocalFilePaymentAuthorityFence(f.settings),/STALE_OR_CONFLICTING/);}finally{f.close();}});
test("disk replay rejects same epoch different source after restart",async()=>{const f=fixture();try{await f.fence.remember(proof());appendFenceRecord(f.settings.filePath,{...proof(),sourceHash:"c".repeat(64)});assert.throws(()=>createLocalFilePaymentAuthorityFence(f.settings),/STALE_OR_CONFLICTING/);}finally{f.close();}});
test("exact repeated disk record remains idempotent after restart",async()=>{const f=fixture();try{await f.fence.remember(proof());appendFenceRecord(f.settings.filePath,proof());const before=fs.readFileSync(f.settings.filePath,"utf8"),restarted=createLocalFilePaymentAuthorityFence(f.settings);assert.equal(await restarted.has(recipient),true);await restarted.remember(proof());assert.equal(fs.readFileSync(f.settings.filePath,"utf8"),before);}finally{f.close();}});
test("disk record reordering cannot regress one recipient epoch",async()=>{const f=fixture();try{await f.fence.remember(proof());await f.fence.remember({...proof(),epoch:2});const lines=fs.readFileSync(f.settings.filePath,"utf8").split("\n");[lines[1],lines[2]]=[lines[2],lines[1]];fs.writeFileSync(f.settings.filePath,lines.join("\n"));assert.throws(()=>createLocalFilePaymentAuthorityFence(f.settings),/STALE_OR_CONFLICTING/);}finally{f.close();}});
test("whole terminal record removal never reopens legacy when configured off",async()=>{const f=fixture();try{await f.fence.remember(proof());const header=fs.readFileSync(f.settings.filePath,"utf8").split("\n")[0];fs.writeFileSync(f.settings.filePath,header+"\n");const restarted=createLocalFilePaymentAuthorityFence(f.settings);assert.equal(await restarted.has(recipient),false);let legacy=0,v2=0;const route=createMonetaryV2EventRouter({enabled:false,fence:restarted,legacyProcessor:async()=>legacy++,v2Processor:async()=>v2++});await assert.rejects(()=>route({userId:recipient}),/NO_LEGACY_FALLBACK/);assert.equal(legacy,0);assert.equal(v2,0);}finally{f.close();}});
test("disabled configured bootstrap rejects every account without authority or token access",async()=>{const f=fixture();try{let network=0,legacy=0;const configured=configureLocalMonetaryV2Payments({env:{SEABYSS_MONETARY_V2_PAYMENTS_ENABLED:"false",SEABYSS_MONETARY_V2_PAYMENT_FENCE_FILE:f.settings.filePath,SEABYSS_MONETARY_V2_PAYMENT_ENVIRONMENT:"sandbox"},config:{nodeEnv:"test",playFabTitleId:"1D0C16"},transport:async()=>{network++;throw new Error("unexpected network");}});const route=configured.attach({legacyProcessor:async()=>legacy++});await assert.rejects(()=>route({userId:"UNRECORDED"}),/NO_LEGACY_FALLBACK/);assert.equal(network,0);assert.equal(legacy,0);}finally{f.close();}});
